@startchen

' Relationships

relationship CompanyHasUser {
}
relationship CompanyHasCompanySettings {
}
relationship CompanyHasTenantSetting {
}
relationship CompanyHasCompanyDomain {
}

relationship UserHasSession {
}
relationship UserHasOAuthAccount {
}
relationship UserHasTwoFactor {
}
relationship UserHasPasswordResetToken {
}
relationship UserHasEmailVerificationToken {
}
relationship UserHasRoleAssignment {
}

relationship CompanyHasContact {
}
relationship ContactHasDeal {
}
relationship UserOwnsDeal {
}
relationship ContactHasActivity {
}
relationship DealHasActivity {
}
relationship UserActsInActivity {
}
relationship ContactHasInvoice {
}

relationship CompanyHasProduct {
}
relationship CompanyHasService {
}
relationship SaleHasSaleItem {
}
relationship ContactHasSale {
}
relationship ProductReferencedInSaleItem {
}
relationship ServiceReferencedInSaleItem {
}
relationship ProductHasInventoryMovement {
}

relationship ContactSignsContract {
}
relationship ContractHasInstallment {
}
relationship InstallmentReceivesPayment {
}
relationship BankAccountSettlesPayment {
}
relationship PlanHasSubscription {
}
relationship CompanyHasSubscription {
}

relationship InvoiceGeneratesRevenue {
}
relationship RevenueCategorizedByCategory {
}
relationship RevenueAllocatedToCostCenter {
}
relationship ExpenseCategorizedByCategory {
}
relationship ExpenseAllocatedToCostCenter {
}

relationship CompanyHasBankAccount {
}
relationship BankAccountHasStatementEntry {
}

relationship CompanyHasIntegration {
}
relationship CompanyHasWebhookEndpoint {
}
relationship WebhookEndpointHasDelivery {
}
relationship CompanyRunsJob {
}
relationship CompanyHasNotification {
}
relationship UserHasNotification {
}

relationship CompanyHasReportSchedule {
}
relationship CompanyHasKPI {
}

' Polymorphic attachment relationships (host entity -> artifact)
relationship HostHasDocument {
}
relationship HostHasCalendarEvent {
}
relationship HostHasTask {
}
relationship HostHasActivityArtifact {
}

@endchen